# Generated by Django 5.0.4 on 2024-05-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_projectdocument_document_type_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='Document/Cover'),
        ),
    ]
