# Generated by Django 5.0.4 on 2024-05-08 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_projectdocument_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='prog',
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.student')),
            ],
            options={
                'db_table': 'student_request',
            },
        ),
    ]
