# Generated by Django 5.0.4 on 2024-05-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_remove_progress_prog_studentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Proposal', 'Proposal'), ('Mini One', 'Mini One'), ('Mini Two', 'Mini Two'), ('Final', 'Final')], max_length=20, null=True),
        ),
    ]
