# Generated by Django 5.0.6 on 2024-05-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_studentrequest_is_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrequest',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
