# Generated by Django 5.0.6 on 2024-05-20 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0006_remove_studentrequest_is_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.project'),
        ),
    ]
