# Generated by Django 5.0.6 on 2024-06-28 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.staff'),
        ),
    ]
