# Generated by Django 5.0.6 on 2024-06-30 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0009_alter_comment_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='user',
        ),
        migrations.AddField(
            model_name='upvote',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.staff'),
        ),
    ]
