# Generated by Django 5.0.6 on 2024-07-27 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0010_remove_upvote_user_upvote_supervisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttype",
            name="mentor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="archives.staff",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staff",
            name="type",
            field=models.PositiveIntegerField(
                choices=[(1, "Supervisor"), (2, "coordinator")], default=1
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="level",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="archives.level",
            ),
        ),
        migrations.AlterField(
            model_name="upvote",
            name="supervisor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="archives.staff"
            ),
        ),
    ]
