# Generated by Django 5.0.6 on 2024-08-04 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0012_academicyear_alter_student_academic_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.level')),
            ],
            options={
                'db_table': 'Program',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='archives.program'),
            preserve_default=False,
        ),
    ]
