# Generated by Django 5.0.4 on 2024-04-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0012_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='academic_year',
            field=models.CharField(blank=True, default='2023/2024', max_length=50, null=True),
        ),
    ]
