# Generated by Django 5.0.6 on 2024-08-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0013_rename_date_created_level_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='ending_year',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='starting_year',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='academic_year',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
