# Generated by Django 5.0.6 on 2024-08-04 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0015_program_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
