# Generated by Django 5.0.6 on 2024-08-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0018_uploadedproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
